### ISSUE TITLE
Transfer Out

### ISSUE THREAD

**Issue by thegecko** [cortex-debug/svd-viewer#3]
With reference to https://github.com/Marus/cortex-debug/issues/736 this extension has now been rebased on the original codebase as of https://github.com/Marus/cortex-debug/commit/056c03f01e008828e6527c571ef5c9adaf64083f

This means all existing SVD functionality to date has been captured including:
- All bug fixes
- Support of multiple debug sessions
- Latest strategy for addr-ranges
- Support for SVD support packs (both when registered directly with this extension or when `cortex-debug` is installed).
__Note:__ this support won't work with other debuggers until the support packs switch to a more generic activation event (e.g. `onDebug`), they currently only register when `cortex-debug` activates.

All previous additions (and some new functionality) have been preserved:
- Support for any debug adapter, not just cortex-debug (achieved by using the `readMemory` and `writeMemory` DAP commands and activating for any debug session)
- Browser support for debuggers running in VS Code for web (e.g. vscode.dev, github.dev, codespaces)
- Support for getting SVD files directly from CMSIS packs via the CMSIS pack asset service (see [README](https://github.com/cortex-debug/svd-viewer/blob/main/README.md#use-the-cmsis-pack-asset-service))

~~Support for the generic [debug tracker](https://github.com/mcu-debug/debug-tracker-vscode) was tried over in #4, but does not work due to the tracker not working in a browser environment. The overhead of a separate package and/or extension outweighs a simple VS Code pub/sub tracker IMO.~~

Support for the debug-tracker extension (if installed) has been added in #6

This [Cortex-Debug Organisation](https://github.com/cortex-debug) was created as a temporary home for extracting and managing this extension and the extension should ideally be transferred out.

I'm keen to continue to maintain the extension and see two options for a new home:

- Transfer this to [mcu-debug](https://github.com/mcu-debug) and request to be a maintainer (cc @marus @haneefdm).
This option aligns with other extensions being extracted from `cortex-debug`
- Transfer this to [Eclipse CDT Cloud](https://github.com/eclipse-cdt-cloud) where Arm and partner organisations work on OSS VS Code extensions for embedded development.
There is interest from Eclipse, companies in the Embedded Special Interest Group and the CDT Cloud Project leads to support this, which may be a better maintenance option with more resourcing.

**Comment by thegecko** [comment]
>  I don't think we can transfer the repo to mcu-debug via github.

If you are an owner of `mcu-debug`, I can initiate a transfer. This is the easiest way to keep the history.

> I will of course add you as a developer

Great, I can then update the IDs/etc.

> Also, how do I test this extension in a browser?

What hardware do you have? I can create an example for usage with the Arm Embedded Debugger which works in the browser.

**Comment by haneefdm** [comment]
> If you are an owner of mcu-debug, I can initiate a transfer. This is the easiest way to keep the history.

Yes, I am the owner. Let me know what I need to do on my end. I will probably be notified by Github?

> What hardware do you have? I can create an example for usage with the Arm Embedded Debugger which works in the browser.

I have an ST F429 Nucleo board that I use for most tests. I also have some Infineon PSoC6 boards (can't remember the exact one)

Btw, I want to make Cortex Debug to also work in the Browser but since we launch external programs, not sure it is feasible. I think Arm tools use something like WebUSB

**Comment by haneefdm** [comment]
FYI: I am in the middle of adding a major feature. It is about to go into Preview (Pre-release) mode in the Marketplace. Probably by this weekend. I also have some very large amounts of refactoring to do and things can go a bit unstable. During that time, I will remove the SVD support once the mcu-debug SVD Viewer extension is alive on the marketplace. I plan on making several Preview releases 1.7.x As you know odd numbered minor releases (I have to tag them) are considered Preview by the marketplace and will not be installed unless users subscribe to them. This is how I do Betas

https://github.com/Marus/cortex-debug/issues/810

I don't see any conflicts with SVD code and most of my changes are in the adapter backend and just one new file in the front-end.

**Comment by thegecko** [comment]
> I have an ST F429

OK, I'll see what I can craft...

> I want to make Cortex Debug to also work in the Browser

The trouble will be GDB. I've seen examples of running this in a browser, but requires a mini linux runtime to be compiled and deployed adding a lot of overhead.

> I think Arm tools use something like WebUSB

We do

**Comment by thegecko** [comment]
> how do I test this extension in a browser?

An example for the F429 can be seen here: https://github.com/thegecko/f429-example

**Comment by thegecko** [comment]
> Yes, I am the owner. Let me know what I need to do on my end. I will probably be notified by Github?

Transfer inititaed, you should get a notification in GitHub.

Once transferred, I'll set up the new package ID (`mcu-debug.svd-viewer`?), mark the older one as deprecated and we need to discuss GitHub secrets for CI deploy to marketplaces. I use org-wide secrets for this purpose, but we could also set them up per-repo.

**Comment by haneefdm** [comment]
I've been waiting and still have not seen an invite in my mailbox. Where should I be looking. Nothing in Trash or Spam either.

**Comment by thegecko** [comment]
I believe you see a banner in GitHub

**Comment by thegecko** [comment]
Just checked and the transfer expires after a day. Tried again and it said I need to have permission to create a repo under the mcu-debug org to make the transfer

**Comment by haneefdm** [comment]
I just cloned your repo and changed the origin. Not quite what I wanted. This does not bring any GitHub settings you may had for this repo
