### ISSUE TITLE
EntryNotFound when using Arm Device-Manager to get svdPath

### ISSUE THREAD

**Issue by yacinbm** [cortex-debug/svd-viewer#9]
Type: Bug Report

**Describe the bug**
- OS and Version: Ubuntu 22.04.6 LTS
- VS Code Version: 1.83.1
- Extension Version: Cortex Debug v1.12.1
- Target Device: Silicon Labs EFR32MG24BXXXF1536
- Other extensions you installed (and if the issue persists after disabling them): Arm Device Manager (yes), C/C++ (yes)

**Issue**
When starting a debug session via Cortex-Debug, in the XPERIPHERAL view, I get the following error message instead of a peripheral list:
![error_svd](https://github.com/cortex-debug/svd-viewer/assets/57112334/d0abdb9c-44b5-4528-9f56-93fb894c9bd9)

**To Reproduce**
1. Setup my peripheral with the following settings:
```"launch": {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "JLink - Launch",
                "cwd": "${workspaceFolder}",
                "executable": "./build/debug/project.out",
                "request": "launch",
                "type": "cortex-debug",
                "interface": "swd",
                "svdPath": "${command:device-manager.getDevicePack}",
                "device": "${command:device-manager.getDeviceName}",
                "runToEntryPoint": "main",
                "gdbPath": "arm-none-eabi-gdb",
                "servertype": "jlink",
                "swoConfig": {
                    "source": "probe",
                    "enabled": true,
                    "swoFrequency": 875000,
                    "decoders": [
                        {
                            "port": 0,
                            "type": "console",
                        }
                    ]
                }
            }
         ]
      }
```
2. Start a debug session with the `JLink - Launch` configuration.
3. Check the `XPERIPHERAL` view.

**Expected behavior**
A list of my device's peripheral in the view.

**Code sample and logs**
```
Cortex-Debug: VSCode debugger extension version 1.12.1 git(652d042). Usage info: https://github.com/Marus/cortex-debug#usage
Reading symbols from arm-none-eabi-objdump --syms -C -h -w <path to my project>/build/debug/project.out
Reading symbols from arm-none-eabi-nm --defined-only -S -l -C -p <path to my project>/build/debug/project.out
Launching GDB: arm-none-eabi-gdb -q --interpreter=mi2
    IMPORTANT: Set "showDevDebugOutput": "raw" in "launch.json" to see verbose GDB transactions here. Very helpful to debug issues or report problems
Launching gdb-server: JLinkGDBServer -singlerun -nogui -if swd -port 50000 -swoport 50001 -telnetport 50002 -device EFR32MG24BXXXF1536
    Please check TERMINAL tab (gdb-server) for output from JLinkGDBServer
Finished reading symbols from objdump: Time: 46 ms
Finished reading symbols from nm: Time: 59 ms
Output radix now set to decimal 10, hex a, octal 12.
Input radix now set to decimal 10, hex a, octal 12.
<my entry point> () at <path to my source file>

Program stopped, probably due to a reset and/or halt issued by debugger
2
Resetting target
SWO enabled successfully.
```

**Additional context**
As you can tell from my settings.json file, I'm using the ARM Device-Manager to resolve which SVD file I need for my device. It correctly identifies it and I can see that it's trying to fetch the correct SVD pack for it, but for some reason, cortex-debug is not able to use it. The SVD part of the configuration was done according to the [official extension documentation](https://marketplace.visualstudio.com/items?itemName=cortex-debug.svd-viewer), by leveraging the ARM Device Manager extension.

**EDIT:**
Since this is an issue related to the SVD viewer, I opened it under this repo, but let me know if the issue should be moved elsewhere.

**Comment by thegecko** [comment]
Thanks for the bug report. I suspect the issue is in a different extension, but I'll investigate...

**Comment by thegecko** [comment]
I can see there is an issue with the space in the vendor name `silicon labs`.

While we investigate further, you should be able to use this as a workaround:

```json
    ...
    "cmsisPack": "SiliconLabs::GeckoPlatform_EFR32MG24_DFP@4.3.0",
    ...
```

Also, I notice you have an entry in your config called `device`. I think this should be `deviceName`.

**Comment by yacinbm** [comment]
Ah-ha! That whitespace was indeed my issue. However, on my end the `device` field is indeed correct, changing it to `deviceName` results in a `Property is not allowed` prompt in my `settings.json`.

**Comment by thegecko** [comment]
> I'll report this in the ARM device manager extension, as it seems to be the culprit. Cheers!

I've fixed this in the latest device manager release, `v1.9.7`
